### ISSUE TITLE
TypeError: postService.getPostsByUserId is not a function

### ISSUE THREAD

**Issue by artificialarea** [jcochran206/artsy-capstone-server#8]
Although everything displays fine when go to URL path `/edit/:postId` or `/posts/:postId`

I get this morgan error in the terminal when I make a **`GET /api/posts/:postId`** api call
```
::1 - - [13/Nov/2020:19:16:39 +0000] "GET /api/posts/13 HTTP/1.1" 200 205
TypeError: postService.getPostsByUserId is not a function
    at /Users/sachased/sandbox/thinkful/artsy-capstone-server/src/posts/posts-router.js:112:21
    at Layer.handle [as handle_request] (/Users/sachased/sandbox/thinkful/artsy-capstone-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/sachased/sandbox/thinkful/artsy-capstone-server/node_modules/express/lib/router/route.js:137:13)
    at /Users/sachased/sandbox/thinkful/artsy-capstone-server/src/posts/posts-router.js:105:17
```

**Comment by jcochran206** [comment]
removed get function that was calling similar service
